services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-app
    environment:
      - VIRTUAL_HOST=michael.brian.dominicatechnologies.com
      - VIRTUAL_PORT=8083
      - LETSENCRYPT_HOST=michael.brian.dominicatechnologies.com
      - LETSENCRYPT_EMAIL=mikkohbrayoh@gmail.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - CONTACT_EMAIL=${CONTACT_EMAIL:-mikkohbrayoh@gmail.com}
    expose:
      - "8083"
    ports:
      - "8083:8083"
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
